"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Migration = exports.PrimaryIdAutoGenerated = void 0;
const typeorm_1 = require("typeorm");
const _1 = require(".");
exports.PrimaryIdAutoGenerated = process.env.DATABASE?.startsWith("mongodb")
    ? typeorm_1.ObjectIdColumn
    : typeorm_1.PrimaryGeneratedColumn;
let Migration = class Migration extends _1.BaseClassWithoutId {
    id;
    timestamp;
    name;
};
__decorate([
    exports.PrimaryIdAutoGenerated()
], Migration.prototype, "id", void 0);
__decorate([
    typeorm_1.Column({ type: 'bigint' })
], Migration.prototype, "timestamp", void 0);
__decorate([
    typeorm_1.Column()
], Migration.prototype, "name", void 0);
Migration = __decorate([
    typeorm_1.Entity("migrations")
], Migration);
exports.Migration = Migration;
//# sourceMappingURL=Migration.js.map