import { BaseClassWithoutId } from ".";
export declare const PrimaryIdAutoGenerated: any;
export declare class Migration extends BaseClassWithoutId {
    id: number;
    timestamp: number;
    name: string;
}
